from pydantic import BaseModel, Field

from app.core.world_state import FactVisibility, GameState
from app.engine.content.world_loader import WorldPack
from app.llm.provider_base import LLMProvider, Message


class QuestDraftStage(BaseModel):
    id: str
    title: str
    description: str = ""
    objectives: list[str] = Field(default_factory=list)
    next_stages: list[str] = Field(default_factory=list)


class QuestDraftTrigger(BaseModel):
    type: str
    id: str
    action: str = "activate"
    objective_id: str | None = None
    next_stage: str | None = None


class QuestDraft(BaseModel):
    title: str
    premise: str
    involved_npcs: list[str] = Field(default_factory=list)
    involved_locations: list[str] = Field(default_factory=list)
    involved_items: list[str] = Field(default_factory=list)
    required_facts: list[str] = Field(default_factory=list)
    stages: list[QuestDraftStage] = Field(default_factory=list)
    triggers: list[QuestDraftTrigger] = Field(default_factory=list)
    rewards: list[str] = Field(default_factory=list)
    risk_flags: list[str] = Field(default_factory=list)
    validation_notes: list[str] = Field(default_factory=list)
    proposed_new_content: dict[str, list[str]] = Field(default_factory=dict)


class QuestDraftValidationIssue(BaseModel):
    code: str
    message: str
    ref_id: str | None = None


class QuestDraftValidationReport(BaseModel):
    ok: bool
    errors: list[QuestDraftValidationIssue] = Field(default_factory=list)
    warnings: list[QuestDraftValidationIssue] = Field(default_factory=list)


def rule_based_generate_side_quest(pack: WorldPack, state: GameState | None = None) -> QuestDraft:
    del state
    npc = pack.npcs[0] if pack.npcs else None
    location = pack.locations[0] if pack.locations else None
    item = next((candidate for candidate in pack.items if candidate.portable), None)
    safe_fact = next(
        (
            fact
            for fact in pack.facts
            if fact.visibility in {FactVisibility.PUBLIC, FactVisibility.DISCOVERABLE}
        ),
        None,
    )
    involved_npcs = [npc.id] if npc else []
    involved_locations = [location.id] if location else []
    involved_items = [item.id] if item else []
    required_facts = [safe_fact.id] if safe_fact else []
    objective_prefix = npc.id if npc else "local"
    return QuestDraft(
        title=f"{npc.name if npc else 'Local'} Errand",
        premise=_safe_premise(npc_id=npc.id if npc else None, location_id=location.id if location else None),
        involved_npcs=involved_npcs,
        involved_locations=involved_locations,
        involved_items=involved_items,
        required_facts=required_facts,
        stages=[
            QuestDraftStage(
                id="ask_about_need",
                title="Ask About the Trouble",
                description="Speak with the involved local and learn what help is needed.",
                objectives=[f"talk_to_{objective_prefix}"],
                next_stages=["resolve_errand"],
            ),
            QuestDraftStage(
                id="resolve_errand",
                title="Resolve the Errand",
                description="Follow the lead and return with a useful answer.",
                objectives=["follow_lead"],
                next_stages=[],
            ),
        ],
        triggers=[
            QuestDraftTrigger(
                type="npc_talked",
                id=npc.id if npc else "",
                action="complete_objective",
                objective_id=f"talk_to_{objective_prefix}",
                next_stage="resolve_errand",
            )
        ]
        if npc
        else [],
        rewards=["small_payment"],
        risk_flags=["candidate_draft", "requires_author_review"],
        validation_notes=["Generated by deterministic rule-based side quest generator."],
    )


def llm_assisted_generate_side_quest(
    pack: WorldPack,
    provider: LLMProvider,
    *,
    temperature: float = 0.2,
) -> QuestDraft:
    draft = provider.generate_json(_messages_for_pack(pack), QuestDraft, temperature)
    report = validate_quest_draft(draft, pack)
    if not report.ok:
        error_text = "; ".join(issue.message for issue in report.errors)
        raise ValueError(f"Generated QuestDraft failed validation: {error_text}")
    return _redact_hidden_fact_text(draft, pack)


def validate_quest_draft(draft: QuestDraft, pack: WorldPack) -> QuestDraftValidationReport:
    errors: list[QuestDraftValidationIssue] = []
    warnings: list[QuestDraftValidationIssue] = []
    npc_ids = {npc.id for npc in pack.npcs}
    location_ids = {location.id for location in pack.locations}
    item_ids = {item.id for item in pack.items}
    fact_ids = {fact.id for fact in pack.facts}
    proposed = draft.proposed_new_content

    _validate_refs(errors, draft.involved_npcs, npc_ids, "npc", proposed.get("npcs", []))
    _validate_refs(errors, draft.involved_locations, location_ids, "location", proposed.get("locations", []))
    _validate_refs(errors, draft.involved_items, item_ids, "item", proposed.get("items", []))
    _validate_refs(errors, draft.required_facts, fact_ids, "fact", proposed.get("facts", []))

    stage_ids = {stage.id for stage in draft.stages}
    for trigger in draft.triggers:
        if trigger.type == "npc_talked" and trigger.id not in npc_ids and trigger.id not in proposed.get("npcs", []):
            errors.append(_issue("missing_trigger_npc", f"Trigger references missing NPC: {trigger.id}", trigger.id))
        if trigger.type == "item_acquired" and trigger.id not in item_ids and trigger.id not in proposed.get("items", []):
            errors.append(_issue("missing_trigger_item", f"Trigger references missing item: {trigger.id}", trigger.id))
        if trigger.type == "fact_discovered" and trigger.id not in fact_ids and trigger.id not in proposed.get("facts", []):
            errors.append(_issue("missing_trigger_fact", f"Trigger references missing fact: {trigger.id}", trigger.id))
        if trigger.type == "location_visited" and trigger.id not in location_ids and trigger.id not in proposed.get("locations", []):
            errors.append(_issue("missing_trigger_location", f"Trigger references missing location: {trigger.id}", trigger.id))
        if trigger.next_stage and trigger.next_stage not in stage_ids:
            errors.append(_issue("missing_next_stage", f"Trigger references missing stage: {trigger.next_stage}", trigger.next_stage))

    hidden_facts = {fact.id: fact for fact in pack.facts if fact.visibility == FactVisibility.HIDDEN}
    player_facing = " ".join([draft.title, draft.premise, *[stage.title + " " + stage.description for stage in draft.stages]]).lower()
    for fact_id, fact in hidden_facts.items():
        hidden_text = (fact.text or "").strip().lower()
        if hidden_text and hidden_text in player_facing:
            errors.append(_issue("hidden_fact_text_leak", f"Draft player-facing text reveals hidden fact: {fact_id}", fact_id))
        if fact_id in draft.required_facts:
            warnings.append(_issue("hidden_fact_reference", f"Draft references hidden fact by id only: {fact_id}", fact_id))
    return QuestDraftValidationReport(ok=not errors, errors=errors, warnings=warnings)


def _validate_refs(
    errors: list[QuestDraftValidationIssue],
    refs: list[str],
    known_ids: set[str],
    ref_type: str,
    proposed_ids: list[str],
) -> None:
    for ref_id in refs:
        if ref_id not in known_ids and ref_id not in proposed_ids:
            errors.append(_issue(f"missing_{ref_type}", f"Draft references missing {ref_type}: {ref_id}", ref_id))


def _messages_for_pack(pack: WorldPack) -> list[Message]:
    hidden_fact_ids = [fact.id for fact in pack.facts if fact.visibility == FactVisibility.HIDDEN]
    return [
        {
            "role": "system",
            "content": (
                "Generate one local side quest draft as structured JSON. Do not modify GameState. "
                "Only reference existing NPC/location/item/fact ids unless proposed_new_content marks them. "
                "Hidden facts may be referenced by id, but their text must not appear in player-facing fields."
            ),
        },
        {
            "role": "user",
            "content": (
                f"NPC ids: {[npc.id for npc in pack.npcs]}\n"
                f"Location ids: {[location.id for location in pack.locations]}\n"
                f"Item ids: {[item.id for item in pack.items]}\n"
                f"Fact ids: {[fact.id for fact in pack.facts]}\n"
                f"Hidden fact ids only, no text: {hidden_fact_ids}"
            ),
        },
    ]


def _redact_hidden_fact_text(draft: QuestDraft, pack: WorldPack) -> QuestDraft:
    hidden_texts = [(fact.text or "").strip() for fact in pack.facts if fact.visibility == FactVisibility.HIDDEN and fact.text]
    payload = draft.model_dump()
    for hidden_text in hidden_texts:
        for key in ("title", "premise"):
            if hidden_text and hidden_text in payload[key]:
                payload[key] = payload[key].replace(hidden_text, "[hidden fact reference]")
        for stage in payload["stages"]:
            if hidden_text and hidden_text in stage["description"]:
                stage["description"] = stage["description"].replace(hidden_text, "[hidden fact reference]")
    return QuestDraft.model_validate(payload)


def _safe_premise(npc_id: str | None, location_id: str | None) -> str:
    if npc_id and location_id:
        return f"{npc_id} needs quiet help following a local lead near {location_id}."
    return "A local lead could become a small side errand."


def _issue(code: str, message: str, ref_id: str | None = None) -> QuestDraftValidationIssue:
    return QuestDraftValidationIssue(code=code, message=message, ref_id=ref_id)
